# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestRoomnametoobig():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_roomnametoobig(self):
    # Test name: room name too big
    # Step # | name | target | value
    # 1 | open | / | 
    self.driver.get("https://www.1234.ie/")
    # 2 | setWindowSize | 550x691 | 
    self.driver.set_window_size(550, 691)
    # 3 | click | css=a:nth-child(2) > .button | 
    self.driver.find_element(By.CSS_SELECTOR, "a:nth-child(2) > .button").click()
    # 4 | click | css=div:nth-child(2) > .JoinInput | 
    self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(2) > .JoinInput").click()
    # 5 | type | css=div:nth-child(2) > .JoinInput | test
    self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(2) > .JoinInput").send_keys("test")
    # 6 | click | css=div > .mt-20 | 
    self.driver.find_element(By.CSS_SELECTOR, "div > .mt-20").click()
    # 7 | type | css=div > .mt-20 | testestestestestestestestestest
    self.driver.find_element(By.CSS_SELECTOR, "div > .mt-20").send_keys("testestestestestestestestestest")
    # 8 | click | css=.button | 
    self.driver.find_element(By.CSS_SELECTOR, ".button").click()
    # 9 | mouseOver | css=.button | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".button")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 10 | assertAlert | Room name too long... | 
    assert self.driver.switch_to.alert.text == "Room name too long..."
  
