name: semgrep

on: [push]

jobs:
  self_test:
    runs-on: ubuntu-latest
    name: run semgrep rules tests
    steps:
      - uses: actions/checkout@v2
      - name: run tests
        id: semgrep-tests
        uses: returntocorp/semgrep-rules-test-action@v0.2
      - uses: actions/upload-artifact@v1
        if: always()
        with:
          name: tests
          path: ${{ steps.semgrep-tests.outputs.output_dir }}